name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Build (Java ${{ matrix.java-version }} on ${{ matrix.os-name }})
    runs-on: ${{ matrix.os-name }}

    strategy:
      fail-fast: false
      matrix:
        os-name: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        shell: bash
        run: ./mvnw -B verify

      - name: Publish to codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        if: always()
